---
title: "Tarea 2"
author: "QO"
date: "2023-11-12"
output: html_document
---

"Librerías que usare" 

```{r}
suppressPackageStartupMessages(library(rio))
suppressPackageStartupMessages(library(sf))
library(ggplot2)
suppressPackageStartupMessages(library(dplyr))
```


```{r}
data_2 <- import("C:\\Users\\ADM\\Downloads\\week2_spatial\\data\\airports.csv")
names(data_2)
```
```{r}
data_5 <- import("C:\\Users\\ADM\\Downloads\\week2_spatial\\data\\navaids.csv")
names(data_5)
```

```{r}
# Convertir los datos en un objeto sf (capa geoespacial)
navaids <- st_as_sf(data_5, coords = c("longitude_deg", "latitude_deg"), crs = 4326, remove = FALSE)
```


```{r}
# Convertir los datos en un objeto sf (capa geoespacial)
airports_sf <- st_as_sf(data_2, coords = c("longitude_deg", "latitude_deg"), crs = 4326, remove = FALSE)
```



```{r}
layer1 <- suppressMessages(invisible(st_read("C:\\Users\\ADM\\Downloads\\week2_spatial\\maps\\World_Cities\\World_Cities.shp")))
layer2 <- suppressMessages(invisible(st_read("C:\\Users\\ADM\\Downloads\\week2_spatial\\maps\\World_Countries\\World_Countries.shp")))
layer3 <- suppressMessages(invisible(st_read("C:\\Users\\ADM\\Downloads\\week2_spatial\\maps\\World_Hydrography\\World_Hydrography.shp")))
```

```{r}
france <- layer2[layer2$COUNTRY == "France", ]
cities_france <- layer1[st_within(layer1, france, sparse = FALSE)[, 1], ]
hydrography_france <- layer3[st_within(layer3, france, sparse = FALSE)[, 1], ]
airports_france <- airports_sf[st_within(airports_sf, france, sparse = FALSE)[, 1], ]
navaids_france <- navaids[st_within(navaids, france, sparse = FALSE)[, 1], ] 
```


```{r}
ggplot() +
  geom_sf(data = france, fill = "lightgray", color = "black", size = 0.2) +
  geom_sf (data = airports_france, color = "red", size = 0.1) +
  geom_sf (data = navaids_france, color = "yellow", size = 0.1) +
 theme_minimal() +
  labs(title = "Mapa de Francia con Ciudades e Hidrografía",
       x = "Longitud", y = "Latitud")
```

```{r}
ggplot() +
  geom_sf(data = layer1, fill = "lightgray", color = "black", size = 0.1) + # Primera capa (e.g., países)
  geom_sf(data = layer2, color = "blue", size = 0.5) + # Segunda capa (e.g., regiones)
  geom_sf(data = layer3, color = "red", size = 1) + # Tercera capa (e.g., Regiones de agua)
  geom_sf(data = airports_sf, color = "yellow", size = 0.0001) + # Tercera capa (e.g., Aeropuertos)
  theme_minimal() +
  labs(title = "Mapa con tres capas geoespaciales", x = "Longitud", y = "Latitud")
```






